// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9tmvCKRcAVXBj320ISNmlJAc5o6a5s3Y',
    appId: '1:734202664291:web:5866f0af3a74c58e2baf56',
    messagingSenderId: '734202664291',
    projectId: 'fine-cb713',
    authDomain: 'fine-cb713.firebaseapp.com',
    storageBucket: 'fine-cb713.firebasestorage.app',
    measurementId: 'G-L7P8LZX637',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGf4J5EKBJoHo40WYPTaDIm0m_oreNsQ4',
    appId: '1:734202664291:android:9e4b31711cf3a89d2baf56',
    messagingSenderId: '734202664291',
    projectId: 'fine-cb713',
    storageBucket: 'fine-cb713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBquMtYXgMLHrD8yf3dCZxVq_Jpci57Tuo',
    appId: '1:734202664291:ios:ad124352ffcd5d642baf56',
    messagingSenderId: '734202664291',
    projectId: 'fine-cb713',
    storageBucket: 'fine-cb713.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9tmvCKRcAVXBj320ISNmlJAc5o6a5s3Y',
    appId: '1:734202664291:web:0890099476b4707e2baf56',
    messagingSenderId: '734202664291',
    projectId: 'fine-cb713',
    authDomain: 'fine-cb713.firebaseapp.com',
    storageBucket: 'fine-cb713.firebasestorage.app',
    measurementId: 'G-E6YYNZSCSQ',
  );
}
